### ISSUE TITLE
found 1 high severity vulnerability

### ISSUE THREAD

**Issue by pritish384** [Dev-CasperTheGhost/ghostybot#254]
**Description**
High            Denial of Service                                             
                                                                                
  Package         css-what                                                      
                                                                                
  Patched in      >=5.0.1                                                       
                                                                                
  Dependency of   google-play-scraper                                           
                                                                                
  Path            google-play-scraper > cheerio > css-select > css-what         
                                                                                
  More info       https://npmjs.com/advisories/1754                             
                                                                                
found 1 high severity vulnerability in 1384 scanned packages
  1 vulnerability requires manual review. See the full report for details.
  
  pls help

**Comment by Dev-CasperTheGhost** [comment]
don't worry about this. That package isn't maintained iirc.
