### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kinez9999** [Dev-CasperTheGhost/ghostybot#270]
> ghostybot@2.0.0 start /home/runner/ghostybot
> BUILD_PATH=true DEV_MODE=false node -r ts-node/register -r tsconfig-paths/register ./dist/index.js

Error: Cannot find module '/home/runner/ghostybot/dist/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._resolveFilename (/home/runner/ghostybot/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghostybot@2.0.0 start: `BUILD_PATH=true DEV_MODE=false node -r ts-node/register -r tsconfig-paths/register ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ghostybot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-26T13_08_04_563Z-debug.log

**Comment by casperiv0** [comment]
> 11. Self Hosting
We won't help anyone with any issues related to setting up GhostyBot yourself or self-hosting.
Always remember to search the error on google or stackoverflow. We believe in FOSS but we are not going to spoonfeed you. Also do not spam to get help.
