### ISSUE TITLE
Proposal: Wait 5 minutes before leave the voice channel at the queue end

### ISSUE THREAD

**Issue by luisfelipesdn12** [Dev-CasperTheGhost/GhostyBot#314]
## Problem
It is kind annoying when we heard the "discord leave" sign just right the last music plays.

## Solution
Would be nice if the bot wait some time for some queue addition before leaving.
And after something like 5 minutes without any action, leave the channel.

**Comment by luisfelipesdn12** [comment]
If you can tell me the file that controls this leaving logic, I can try to implement the delay :)

**Comment by LackyPal** [comment]
It uses [Distube](https://distube.js.org) for music system. As of distube, it's not possible to do that now

**Comment by casperiv0** [comment]
Seems like this isn't possible at the moment with Distube. Will be closing issue here, you can open an issue at https://github.com/skick1234/DisTube and request this feature.
