### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by sabyr-cpu** [Dev-CasperTheGhost/GhostyBot#321]
**Describe the bug**
Commands don't work and show "This interaction failed message"

**Command**
any command

**To Reproduce**

1.execute any command

**Expected behavior**
expected to work

**Screenshots**
![image](https://user-images.githubusercontent.com/60884110/145350978-7579970d-910a-434e-8580-13d3ac84b3a5.png)

**Comment by casperiv0** [comment]
I made an announcement in the Discord server:

```
GhostyBot will be down for some time. Going to be doing some maintenance. 

Sorry for the inconvenience.
```

**Comment by sabyr-cpu** [comment]
ok, thank you and sorry for disturbing
