### ISSUE TITLE
Cant start bot

### ISSUE THREAD

**Issue by Abheeshtyadav** [Dev-CasperTheGhost/GhostyBot#356]
This error comes when starting bot 

 npm install @components/modal @config/discord-config assets @components/Footer src handlers models @components/reaction-role react-i18next @components/Switch @config/APIs utils @components/Loader @components/AlertMessage @scripts/generateCommandList structures @components/Navbar
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@components%2fmodal - Not found
npm ERR! 404 
npm ERR! 404  '@components/modal@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-02-23T07_00_15_840Z-debug.log
exit status 1

Replit: Package operation failed.

how can i fix it 
i tried npm install not workibg after that also

**Comment by casperiv0** [comment]
We don’t provide self hosting support
